language: python
deploy:
  provider: releases
  api_key:
    secure: lUtWJJSHoSp9HD5e68Gd2VKQJR3DXij0/KIzpehVCqw0rHlJoLfVgYG6AfB1EjdFsio7z8bDiBeXYcEpCTCxhNbgAzDLW530HcV/uqt4RaF0DHzcumDimxfcUZGQua0lcfWlbQ5W7ZRSSlCyjKR/aMnpUBph9kTzhyLuntsKr1so346XFVUa3E0bQPCzZcGXKil52e7uzWAuXz4Dy+7Fajr3dmvkfzClo6UQKQ6SfKjnPQBa1wqMfzUOhQhpvyiyWCRYGojUi0U8zyWRRp/bdkqyf2ZkSf71fJdylEplr5xuAuaUP8QBavF5/MgVHxJOe/jxywLdBXXQKI+HjrxNRVBXHIqnxeObtNRe4BJAX9K4x/81kuxW1sSqrJPX/O0cQM4LagjrXIJIjXiPScIgpccpK6XzGz7WmTm7noTbnrQFDcUlm1nKBUbZgjTqGdNHUcNYai6IG/e8PZMN2BdimCV9BE4YmTOZqHYGepWQpHsRB9AvfZmPR81B4rx0aR4/nABaL4/v3LvjVyiToljwXUSb+BYikY+FHRZjHFx+KnyqHlb0P2uajwHEXE8axfy79QF4jg7lOxM6JQp8/APnIDanUXZ9eJoqlBsvbkme2ZhzgQKYsGxnOoygdedef853frdxZ4svIIMCppGiz5q2/YZzVLKESEVom2oTfWFfwPU=
  file: ''
  on:
    repo: Pras360/aaa
