language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
env:
- PLATFORMIO_CI_SRC=src/
install:
- pip install -U platformio
- platformio update
script:
- platformio run -e nodemcuv2_deploy
- platformio --version

deploy:
  on:
    repo: fahmikhl/myota
    tags: true
    all_branches: true
    condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
  skip_cleanup: true
  provider: releases
  overwrite: true
  api_key:
    secure: AB+3RmtS1FCbrgbt8d7f9Fr5iPXKjewzqDcfn2tPEUR37hRHIyXD0zJDDDcsFj2FHLBu28nmz+NOS59QaGOTrHLj0Uitgr4C4lA5TV7laLkGzDHW00iMP9Aad0r9tvrbzkuMHOdXxc1bk8k5MQ33huQMWAuHPCEKxVZ2I/n3sW3MWZ6Q+fL6rt5GpJqSfYTkBYlZvHarjiuSEefef5vfa1DZbLY/qmwAdFCV3atFx6YHSAPpt+ZXPu3ch6TWth2Q0MyAjGQO3neP4amNFjHpuwfeS1fb5hoMWcRiBhnT306eDc5uX3SD0uTWVRz1JgqTlhAlT6nNcNwrhsGd8pVlXQM4yPBzgIuZSdeAUKYv0Gqy2Nbc9nFPJJRwXib3PQ8s2Fuq5KXs/FiPj/+H18nJ/EG0EBcnQpI11SoJ128JLvDKJOHFwA9tld24nzEFtQifiQRk/aSIrKy5QD39hjOYHwTSLrDp1OMS+sCAEvfdsgZixVT28sEZR8TbJO656VRk+LORev03/8ePcxHhFnescUGXN/ExVjhhh8CLISP1HjU7Bx9meh3+cBK4NGgIbSSOhLYsqT6FBdR9c/tkKC/rlMP6t9V7KtzTEAJ++S8WP0p7tqqTGNM2ShuZtOPn+4KP4XgS5lhRILQOyyChLqeFYHqB3TqTdX0OJQbLwdtv8JE=
  file: ".pio/build/nodemcuv2_deploy/firmware.bin"

