  language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
env:
- PLATFORMIO_CI_SRC=src/

before_install:
- export TZ=Asia/Jakarta



install:
- pip install -U platformio
- platformio update 
- platformio lib install 415
- platformio lib install 64@5.13.4
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%y%m%d%H%M%S')}

script:
- platformio run -e nodemcuv2_deploy
- platformio --version
 
deploy:

  on:
    all_branches: true
  name: stable
  skip_cleanup: true
  provider: releases
  overwrite: true
  api_key:
    secure: huUzBWcp1732b5038IlBKrX9ElQpM3Z6DVCNsUHsJ9xlwFseNHOWXoZNx2CHKJ8mhAgNe0oGOzJUFBP/BQYhjJdfokJ6/6+ipuMSimV2b3qfVCeaZJlsF2MpKE7N++H4pFPk3SQcBN9xBPIoaLD65fbBLuiXX68cwm0yAJUeX182qPOu9N9krs4+ljdGQfMza7l36Wv9fyMfObAEydT6dDPbcA7/QI9mZOa7l5kYpTw1ftVKGTLCMLwOH2zlKYp4SQoKn6bgEBGFVGmSjt0+mTylD1dxVFkVoS6Q2IFAWS6CNIQ6MdMQ/8t/JJhbJFUfhUR0RM9ycO9nNXA3QW1NMZHd5FaaGCnXEgSjok6kiW65AWZeq7RuCRamfk349fcOul47YRUEkf3xth397WVDKxue5Y7z0XlKb9w62VukNMTM+/c/W5DKS8sdDME/aB0emvIu9ibbM18p9oKV/2u8lHPOf46zcegtE+8/aYfL3nhMdDTcnwsSR77IZmVFmy6nTo1m7jEix3NxPe/nrQ+ShhlTajuoNBonG67qaiauMxZZ5juwkTLP1E6skNcMpsoNtRU4RaCMtOuuWqRK/MaVwEm2YJDd80JNFaZcANzoaZ/ms7cwrFRc2+TOlIorixjp8u/akH7ao2DmhtXf3/96OGhyPCrSR8W1TrOmuImig+4=
  file: ".pio/build/nodemcuv2_deploy/firmware.bin"