  language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
env:
  global:
    secure: KzdfnPc3sreNEHGuMu1ZCXj+vuNYiRfPmcbGULoRa3MojTiSRJEU3kBbKk53phy/dAjZ2SXy4nQcgsZDAaOgStzULN0nIJ7qwLS6gNdqhdjDAhmV9kUiXgxQH/o54yoU5KmpSwEw0irSpfJ/ZQrMS+uPnx+GTLs1LyLhAeNQS8RNkwsQ6aX0Mu9R76qSBZ7WgGQW34oKKcuyaoi/EJODvU5sEK6ugEB7JFtgCj7YHbdyHRVbbFodtZI/9pQSA7i/7lvY96fPr5Jc67RcISobEgSfdSJmBxtERrmMJy4cHBzglxnjxhGYvHPaePnzmo3idwGvgEQtSe1xTdMzrffNTyxygbJErG98CHR64aDbkZ0hfDZYyox852RuZi3hjORY67hh/TIVGADFQCW6psT4NtQqlBIsTHHS8F1gA8wjXB/ZY/1Aa7NGVUP8jFtkQZojFASqBTkPT1Acv8hgqgxKOu0yb8wuGt/GuCctNN1Klmb8OcLexbcSiip9L2VO0N8UcqeNIZmMWh3u/6wG+P5/3rdUO1O8yzee0J5hKPR/uwdRT7Sdni0WEIhFeyHwSAZEYrzy1Dgw+xGrswdW1qVxnAdZT27joZaC8KLiq1SlPFEub8hAPNV77coifz8Jgm78RWQXP45Elz7a981vJlMjpv2MhI5Mrh1ryGl4b5rtk+8=

before_install:
- export TZ=Asia/Jakarta

install:
- pip install -U platformio
- platformio update 
- platformio lib install 415
- platformio lib install 64@5.13.4
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%y%m%d%H%M%S')}

script:
- platformio run -e nodemcuv2_deploy
- platformio --version

deploy:
  #name: stable
  skip_cleanup: true
  provider: releases
  overwrite: true
  api_key:
    secure: O9ixTBF+9hARkbu2ldlsjRkEm7AtJEkp083AD0AQb2O8mMv98DldufmcFmbIJ1GPus6k57PpQfOprOizXSnCVbbYvSnrx9QgKZaq9im39l3WuYFLpxNNhXvurypeUS79W5Wd9snk7ogBZ9Nbjkim+5TzA0iPK+wmv9BENY3x6iSxcW87dqmlc5NhVzdyowU7EkUJ0gWviDeg//yfWYXFf0l7NfuaKK70WxbMA1301M7QWr4+IxTsCHkkuvBd7v3QZBw+duzBhT4pRrZ3v4buRTpWheP+EQ76yVymJgUxw1jm7ZUvuM2s2OOydgPbbfujSXz4g0A3r5p29gbFiOB9+wQN1u9pCSALZh5DkL8Ft9in7wrkB1Zw2iQvA62Aq5XCJqR+3uE3lfxu6PxObDH6mPLiNJzsHBURcNckXlM72sw5eiePfKxM/Lskj2IgVZnk01fFXDqIyG0j8hbzWuRRLIVzjO0imXOSYYDeynCIDSXQkaO3bmfRoJUiPx8AzcUEZOnsmtlsLJtk28EjUdlfoJRx295dzx6xE6+eRLD8ktUYnafVjKvSP43k22glTHjLIwEzUXinoXstD4ouIRUaS9fksjKLSeZm23P2B85q/vhm9r76HiNCtENEWmiLH9bNwE06wWOInzgcMkQ+VrCJ856amttr2iq/HFvI9HZrHss=
  file: 
  -"README.md"
  -".pio/build/nodemcuv2_deploy/firmware.bin"
  on:
  tags: false
  all_branches: true
    repo: Pras360/aaa