  language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
env:
- PLATFORMIO_CI_SRC=src/

before_install:
- export TZ=Asia/Jakarta

install:
- pip install -U platformio
- platformio update 
- platformio lib install 415
- platformio lib install 64@5.13.4
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%y%m%d%H%M%S')}

script:
- platformio run -e nodemcuv2_deploy
- platformio --version

deploy:
  provider: releases
  api_key:
    secure: JYMOEDkBIFh1If/Bxa9wfj7FnN0NEEA9saDra+LcdnRKA6olZZTtnl/VlC1BNRidm04VutzPQ0L5qRf/qSzNIaVq8XhQJS3tOY81n1RuOcXt7njfcKOyhRNHz6etRyFFzM40ORbLehn9jkKQS/t2M/GftSiZcA15dEQNiHUiSUBbmmETBukkHB0BMAeQlyjv3sOn9sOO8E/0fWRH2jMZeug84m5ZQufTidCY5sDK5RbNv8ywki0TiB7jU9FbLFz8rmhnMQ98Pt55mwHUZvj/Ci23vjcVLTzx5KzbWT9A6WruW7+AQk4ZFKilW+BfMtelY1MnOEV46yQVUapSllYxLInmLYiLUKEZZhm4uDUDJsXJMFTG299cN5J4CHUw7XKabMrTtN8XT+Vbcc6a6vzbZUtiy1K5vtoVPyFlrsYdF4j+me19bm020O/K/IscDqWThoBP9rRzpFAjy+u3hMSKqvyqbI/AwiNJzwslRh4qS9+qpWllX229z9uH1pp14gDAy4Om+JVgVDjKY5PNqzWFZVMU3AHACgcRW9rQcUBEtvS5YFavfqf1zF5oZpgYFHvSBI+o63e/V2ChybWkDFRGvOQHt+IIFhq4YzQmtY6Hg2zqgwOE39OvjPq4hhEfGOYuxIQLKpq9GHY/6dZH6vmIWLElnw1bMD0w26aRG5cOd4o=
  file: ".pio/build/nodemcuv2_deploy/firmware.bin"
  on:
    repo: Pras360/aaa