  language: python
python:
- '2.7'
sudo: false
cache:
  directories:
  - "~/.platformio"
env:
- PLATFORMIO_CI_SRC=src/

before_install:
- export TZ=Asia/Jakarta

install:
- pip install -U platformio
- platformio update 
- platformio lib install 415
- platformio lib install 64@5.13.4
- export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%y%m%d%H%M%S')}

script:
- platformio run -e nodemcuv2_deploy
- platformio --version
 
deploy:

  on:
    all_branches: true
  name: stable
  skip_cleanup: true
  provider: releases
  overwrite: true
  api_key:
    secure: ZVzAvQmAmYzxViTNN/YwSgyJHY84NMMGu1LmznJcjw76/pV4aBx89Eh+WMTxBtrxJdBnRlf2O5xatYlheL2K2yf1uO0foMoYGf7WnysPlW9h4CbR3FCGQ6eN7zZsEtr3uigKvLQRbY2CWfor8VjYnKqU47OAvVK3iVf5jI81Dg3A6f8LIyOT04Bi0U+zKTFmWI7vFYg+/cIfhVh2jOfyhuCpP7SlZ5oBoPZgk1MAPYQpVahs6T+SlFjT9NThUWfLbDJwZfLqx7ayfEKStShSifHMPOqlntVA99Nxtz6A4+0o79UeSk9F+WB5kyy0Tvn5Y8PGu7RHMH3cr8G+MxXgijCmAChFZc5NghM00zPG3chVeYG5NotYTsYZtRKhrpfQ2hEoIA1k+oxpRof3ohwfFDwKZFej9zwYPEXnqc7h5Mz2afYtYAwKvduqJLjmfuRymVfFNsTVAWVsMN4gJXDONIfZCF+nNY4XPhb3q5WyNGqGLTJEvgIxJi5GzG9IER8lG+pzamxirsXjuzPGQnO/vCCtncVvRECJ9nejRjeglAvDLC5/RoRhl4ymhehJ7YmkftCn5JcNPUCaDeL2ZJV9frrMZAJIaI017cZ8J9w3agXJVVQni+mSgrH4U6sCNvsUTWLCYHpteNE/7r7mSS1mr8CGm3G6YAxorvHnquL18Qs=
  file: ".pio/build/nodemcuv2_deploy/firmware.bin"